config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users

  resources :categories, only: [:index, :show] do
    resources :items, except: [:index]
  end

  resources :items, except: [:index] do
    resources :reviews, except: [:show]
  end

  resources :reviews do
    resources :upvotes, only: [:create]
    resources :downvotes, only: [:create]
  end

  resources :searches, only: [:index]

  resources :users, only: [:index, :update, :destroy]
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @search_results_item = Item.search(params[:search])
    @search_results_review = Review.search(params[:search])
  end
end

app/views/searches/index.html.erb
<div class="text-center category-header">
  <h4> Search Results </h4>
</div>
<div class="container">
  <div class="row">
    <div class="field columns small-3">
      <ul>
        <% if params[:search].empty? || @search_results_item.empty? && @search_results_review.empty?%>
          <p>No Results</p>
        <% else %>
          <li>Showing Results for <div class="blue-text"><%= params[:search]%></div></li>
          <% if @search_results_item.present? %>
            <p>Item Results</p>
            <% @search_results_item.each do |result| %>
              <li><%= link_to result.name, item_path(result) %></li>
            <% end %>
          <% end %>
          <% if @search_results_review.present? && @search_results_item.present? %>
            <HR WIDTH="90%">
          <% end %>
          <% if @search_results_review.present? %>
            <p>Review Results</p>
            <% @search_results_review.each do |result| %>
                <li><%= link_to result.item.name, item_path(result.item) %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <br>
</div>