config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users

  resources :categories, only: [:index, :show] do
    resources :items, except: [:index]
  end

  resources :items, except: [:index] do
    resources :reviews, except: [:show]
  end

  resources :reviews do
    resources :upvotes, only: [:create]
    resources :downvotes, only: [:create]
  end

  resources :searches, only: [:index]

  resources :users, only: [:index, :update, :destroy]
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  belongs_to :category
  has_many :reviews

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :image, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :user, presence: true

  paginates_per 5
  max_paginates_per 100

  def self.search(search)
    where('name ILIKE ?', "%#{search}%") |
      where('description ILIKE ?', "%#{search}%")
  end

  def votes_order
    reviews.sort_by { |review| review.total_score }.reverse!
  end

  def admin?
    role == "admin"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @category = Category.find(params[:category])
    @items = @category.items.order(created_at: :desc).page params[:page]
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @user = current_user
    @item.user = @user

    if @item.save
      flash[:accepted] = "Item Added!"
      redirect_to item_path(@item)
    else
      flash[:errors] = @item.errors.full_messages.join(". ")
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @reviews = @item.votes_order
    @user = current_user
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    authenticate_user!
    @user = current_user
    @item = Item.find(params[:id])

    if @item.update(item_params) && @item.user == @user
      flash[:accepted] = "Item updated."
      redirect_to item_path(@item)
    else
      flash[:errors] = @item.errors.full_messages.join(". ")
      @item = Item.find(params[:id])
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @category = @item.category
    @item.destroy
    flash[:accepted] = "Item deleted."
    redirect_to category_path(@category)
  end

  protected
  def authorize_user
    @item = Item.find(params[:id])
    if !(current_user.admin? || @item.user == current_user)
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  def item_params
    list = [:name, :description, :image, :purchase_url, :category_id]
    params.require(:item).permit(list)
  end
end

app/views/items/_form.html.erb
<div class="container">
	<%= form_for @item do |f| %>
		<div class="row">
			<div class="field columns small-3">
				<%= f.label :name, 'Item Name' %>
				<%= f.text_field :name, class: "text-field" %>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="field columns small-6">
				<%= f.label :description %>
				<%= f.text_area :description, class: "text-field" %>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="field columns small-6">
				<%= f.label :purchase_url, "Where can you Purchase it?" %>
				<%= f.text_field :purchase_url, class: "text-field" %>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="field columns small-6">
				<%= f.label :image, 'Image URL' %>
				<%= f.text_field :image, class: "text-field" %>
			</div>
		</div>
		<div class="row">
			<div class="field columns small-2 item-category">
				<%= f.label :category_id %>
				<%= f.collection_select(:category_id, Category.all, :id, :name_for_select, prompt: true, class: "item-category") %>
			</div>
		</div>
		<div class="row">
			<%= f.submit "Submit", class: "submit-form" %>
		</div>
	<% end %>
	<br>
</div>

app/views/items/_index.html.erb
  <%- @items.each do |item| -%>
  <div class="text-center">
      <%= link_to image_tag(item.image, size: "300x300"),
          item_path(item) %>
      <h3><%= link_to item.name.capitalize, item_path(item) %></h3>
      <hr>
  </div>

  <%- end -%>

<%= paginate @items %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<br>
<%= render partial: 'form', object: @item %>
<br>
<br>
<%= link_to "Back to item", item_path(@item) %>

app/views/items/new.html.erb
<div class="text-center category-header">
  <h4>Add New Item</h4>
</div>

<%= render partial: 'form', object: @item %>

app/views/items/show.html.erb
<div class="text-center category-header">
  <h4><%= @item.name %></h4>
</div>
<div class="row">
  <div class="columns small-8">
      <br>
    <div><img src=<%= @item.image %>></div>
    <br>
    <% if @item.description.present? %>
        <div class="text-center">
          <%= @item.description.capitalize %>
        </div>
    <% end %>
    <ul>
      <% if current_user %>
        <% if current_user.admin? || (@item.user == current_user) %>
          <li class="text-center"><%= link_to "Edit Item", edit_item_path(@item) %> |
              <%= link_to "Delete Item", item_path(@item), method: :delete %></li>
        <% end %>
      <% end %>
      <br>
    </ul>
  </div>

  <div class="right_text columns small-4 end right-nav">
    <br>
      <h4> Talk </h4>
      <p><%= link_to "Add Review", new_item_review_path(@item), class: "add-review" %></p>

    <div class="container">

        <% if @reviews.present? %>
              <% @reviews.each do |review| %>
                <ul>
                  <div class="row">
                    <div class="columns small-6">
                      <li><%= review.description.capitalize %></li>
                      <li>Rating: <%= review.rating %></li>
                        <% if current_user %>
                          <% if @user.admin? || (@user == review.user) %>
                            <li class="small-font"><%= link_to "Edit", edit_item_review_path(@item, review) %> or
                            <%= link_to "Delete", review_path(review), method: :delete %></li>
                          <% end %>
                        <% end %>
                    </div>
                    <div class="columns small-6 right">
                      <% if current_user %>
                        Votes: <span class= 'vote-total'><%= review.total_score %></span>
                        <br>
                        <%= link_to image_tag("http://i.imgur.com/PmgCU9S.png", class: "vote-image"), review_upvotes_path(review), class: 'upvote' %>
                        <%= link_to image_tag("http://i.imgur.com/VREp02Z.png", class: "vote-image"), review_downvotes_path(review), class: 'downvote' %>
                      <% end %>
                    </div>
                    <br>
                  </div>
                </ul>
              <% end %>
              <br>
        </div>
      <% end %>
    </div>
  </div>
</div>