config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users

  resources :categories, only: [:index, :show] do
    resources :items, except: [:index]
  end

  resources :items, except: [:index] do
    resources :reviews, except: [:show]
  end

  resources :reviews do
    resources :upvotes, only: [:create]
    resources :downvotes, only: [:create]
  end

  resources :searches, only: [:index]

  resources :users, only: [:index, :update, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items

  validates :name, presence: true, uniqueness: true

  def name_for_select
    name.capitalize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @items = @category.items.order(created_at: :desc).page params[:page]
  end
end

app/views/categories/index.html.erb
<div class="row">
  <% @categories.each do |category| %>
    <div class="columns small-4">
      <div class="sit-image">
        <%= link_to image_tag(category.image),
            category_path(category)%>
      </div>
      <div class="hidden-text">
        <%= link_to (category.name),
            category_path(category)%>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<p>
  <h4 class="text-center category-header"><%= @category.name.capitalize %></h4>
</p>
<div class="text-center">
  <%= link_to 'Add New Item', new_category_item_path(@category) %>
  <hr>
</div>

<p>
  <%- if !@category.items.empty? -%>
    <%= render 'items/index', object: @items %>
  <%- end -%>
</p>