config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users

  resources :categories, only: [:index, :show] do
    resources :items, except: [:index]
  end

  resources :items, except: [:index] do
    resources :reviews, except: [:show]
  end

  resources :reviews do
    resources :upvotes, only: [:create]
    resources :downvotes, only: [:create]
  end

  resources :searches, only: [:index]

  resources :users, only: [:index, :update, :destroy]
end

app/views/layouts/_search.html.erb
<%= form_tag searches_path, :method => 'get' do %>

  <div>
    <%= text_field_tag :search, params[:search], placeholder: "Search...", class: "search-bar-only" %>
    <%= button_tag "Search", class: "hidden-button" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeasonSurvey</title>
<link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,400italic,300italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name logo">
        <h1><a href="/"><img src="http://i.imgur.com/NWvEFHJ.png"></a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li class="has-form">
          <div class="row collapse">
            <%= render "layouts/search" %>
          </div>
        </li>
          <li><%= link_to 'Create Item', new_item_path %></li>

        <%- if current_user -%>
          <%- if current_user.role == "admin" -%>
            <li><%= link_to 'Admin', user_registration_path %></li>
          <% end %>

          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Profile', edit_user_registration_path %></li>
          <li class="profile-photo"><%= link_to image_tag(current_user.profile_photo), edit_user_registration_path %></li>

        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>


      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %> text-center">
      <%= value %>
    </div>
  <%- end -%>
  <div class="container background-grey">
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>

</body>
</html>